#!/usr/bin/env python3
import os
import sys
import json
import subprocess
import ipaddress
import shutil
from pathlib import Path
from datetime import datetime

# ================= 📦 全局配置 =================
CACHE_FILE = "wg-manager.json"
CONFIG_DIR = Path("wireguard-configs")
# ===============================================

def run(cmd, inp=None):
    """执行系统命令并返回输出"""
    return subprocess.run(cmd, capture_output=True, text=True, check=True, input=inp).stdout.strip()

def prompt(msg, default=None, is_int=False, is_bool=False):
    """交互式输入辅助函数"""
    while True:
        suffix = f" [{default}]" if default is not None else ""
        val = input(f"👉 {msg}{suffix}: ").strip()
        if not val and default is not None:
            val = str(default)
        if not val:
            print("   ❌ 输入不能为空，请重新输入")
            continue
        
        if is_int:
            try: return int(val)
            except ValueError: print("   ❌ 请输入有效的整数"); continue
            
        if is_bool:
            if val.lower() in ['y', 'yes', 'true', '1']: return True
            if val.lower() in ['n', 'no', 'false', '0']: return False
            print("   ❌ 请输入 y 或 n"); continue
            
        return val

def get_ip_from_subnet(subnet_str, offset):
    """根据子网和偏移量计算 IP"""
    if not subnet_str: return ""
    try:
        net = ipaddress.ip_network(subnet_str, strict=False)
        return str(net.network_address + offset)
    except ValueError:
        return None

class WGManager:
    def __init__(self):
        self.cache = self._load_cache()
        CONFIG_DIR.mkdir(parents=True, exist_ok=True)
        (CONFIG_DIR / "server").mkdir(exist_ok=True)
        (CONFIG_DIR / "clients").mkdir(exist_ok=True)

    def _load_cache(self):
        if Path(CACHE_FILE).exists():
            with open(CACHE_FILE, 'r') as f:
                return json.load(f)
        return None

    def _save_cache(self):
        with open(CACHE_FILE, 'w') as f:
            json.dump(self.cache, f, indent=4)

    def generate_server_conf(self):
        """根据缓存重新生成服务端配置文件"""
        srv = self.cache['server']
        clients = self.cache['clients']
        
        addr_v4 = f"{get_ip_from_subnet(srv['subnet_v4'], 1)}/{ipaddress.ip_network(srv['subnet_v4']).prefixlen}" if srv['subnet_v4'] else ""
        addr_v6 = f"{get_ip_from_subnet(srv['subnet_v6'], 1)}/{ipaddress.ip_network(srv['subnet_v6']).prefixlen}" if srv['subnet_v6'] else ""
        addresses = ", ".join(filter(None, [addr_v4, addr_v6]))
        
        conf = f"""# WireGuard Server Configuration
# Generated by wg-manager.py on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

[Interface]
PrivateKey = {srv['private_key']}
Address = {addresses}
ListenPort = {srv['listen_port']}
# 提示: 部署时请取消下方注释以开启 NAT 转发 (假设出口网卡为 eth0)
# PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
# PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
"""
        for name, c in clients.items():
            conf += f"\n# Peer: {name}\n[Peer]\nPublicKey = {c['public_key']}\n"
            if srv.get('psk'):
                conf += f"PresharedKey = {srv['psk']}\n"
            
            allowed_ips = []
            if c['ip_v4']: allowed_ips.append(f"{c['ip_v4']}/32")
            if c['ip_v6']: allowed_ips.append(f"{c['ip_v6']}/128")
            conf += f"AllowedIPs = {', '.join(allowed_ips)}\n"
            
        path = CONFIG_DIR / "server" / f"{srv['interface']}.conf"
        path.write_text(conf)
        os.chmod(path, 0o600)

    def generate_client_conf(self, name):
        """生成单个客户端配置文件"""
        srv = self.cache['server']
        c = self.cache['clients'][name]
        
        addr_v4 = f"{c['ip_v4']}/32" if c['ip_v4'] else ""
        addr_v6 = f"{c['ip_v6']}/128" if c['ip_v6'] else ""
        addresses = ", ".join(filter(None, [addr_v4, addr_v6]))
        
        conf = f"""[Interface]
PrivateKey = {c['private_key']}
Address = {addresses}
DNS = {c.get('dns', '1.1.1.1')}

[Peer]
PublicKey = {srv['public_key']}
"""
        if srv.get('psk'):
            conf += f"PresharedKey = {srv['psk']}\n"
            
        conf += f"""Endpoint = {srv['endpoint']}:{srv['listen_port']}
AllowedIPs = {c.get('allowed_ips', '0.0.0.0/0, ::/0')}
PersistentKeepalive = 25
"""
        c_dir = CONFIG_DIR / "clients" / name
        c_dir.mkdir(exist_ok=True)
        
        path = c_dir / f"{name}.conf"
        path.write_text(conf)
        os.chmod(path, 0o600)
        
        key_path = c_dir / "private.key"
        key_path.write_text(c['private_key'])
        os.chmod(key_path, 0o600)

    def show_qrcode_from_file(self, file_path):
        """从指定文件路径读取并打印二维码"""
        path = Path(file_path)
        if not path.exists():
            print(f"❌ 找不到配置文件: {path}")
            return
            
        conf_text = path.read_text()
        print(f"\n📱 配置文件 [{path.name}] 的终端二维码 (请用手机 WireGuard 扫描)：")
        print("-" * 50)
        
        # 方案 1: 优先使用系统命令 qrencode (带颜色，识别率最高)
        try:
            subprocess.run(["qrencode", "-t", "ANSI256UTF8", "-m", "2"], input=conf_text, text=True, check=True)
            print("-" * 50)
            return
        except FileNotFoundError:
            pass
        except subprocess.CalledProcessError:
            pass

        # 方案 2: 降级使用 Python qrcode 库的 ASCII 模式
        try:
            import qrcode
            qr = qrcode.QRCode()
            qr.add_data(conf_text)
            qr.print_ascii(invert=True)
            print("-" * 50)
            return
        except ImportError:
            pass

        # 方案 3: 都没有，给出提示
        print("⚠️ 无法生成二维码。请在系统中安装 qrencode 或 python3-qrcode：")
        print("   👉 Ubuntu/Debian: sudo apt install qrencode")
        print("   👉 CentOS/RHEL:   sudo yum install qrencode")
        print("   👉 或者使用 pip:  pip3 install qrcode")
        print("-" * 50)

    def show_qrcode(self, name):
        """通过客户端名称查找配置文件并打印二维码"""
        if name not in self.cache['clients']:
            print(f"❌ 找不到客户端 {name}")
            return
        conf_path = CONFIG_DIR / "clients" / name / f"{name}.conf"
        self.show_qrcode_from_file(conf_path)

    # ================= 🛠️ 命令实现 =================

    def cmd_init(self):
        if self.cache:
            ans = input("⚠️ 已存在配置文件，是否覆盖并重新初始化？(y/N): ")
            if ans.lower() != 'y':
                print("取消操作。")
                return

        print("\n🚀 开始初始化 WireGuard 服务器...")
        
        interface = prompt("服务器接口名称", "wg0")
        endpoint = prompt("服务器公网地址 (域名或IP)", "vpn.example.com")
        port = prompt("监听端口", 51820, is_int=True)
        
        subnet_v4 = prompt("IPv4 虚拟网段", "10.8.0.0/24")
        subnet_v6 = prompt("IPv6 虚拟网段 (留空则不启用)", "")
        
        client_name = prompt("第一个客户端名称", "client01")
        dns = prompt("客户端 DNS", "1.1.1.1, 8.8.8.8")
        allowed_ips = prompt("客户端 AllowedIPs (全流量: 0.0.0.0/0, ::/0)", "0.0.0.0/0, ::/0")
        use_psk = prompt("是否启用预共享密钥 (PSK) 抗量子攻击？(y/N)", "n", is_bool=True)
        
        print("\n🔧 正在生成密钥和配置...")
        srv_priv = run(["wg", "genkey"])
        srv_pub = run(["wg", "pubkey"], srv_priv)
        psk = run(["wg", "genpsk"]) if use_psk else ""
        
        c_priv = run(["wg", "genkey"])
        c_pub = run(["wg", "pubkey"], c_priv)
        
        ip_v4 = get_ip_from_subnet(subnet_v4, 2)
        ip_v6 = get_ip_from_subnet(subnet_v6, 2)
        
        self.cache = {
            "server": {
                "interface": interface,
                "endpoint": endpoint,
                "listen_port": port,
                "subnet_v4": subnet_v4,
                "subnet_v6": subnet_v6,
                "private_key": srv_priv,
                "public_key": srv_pub,
                "psk": psk
            },
            "clients": {
                client_name: {
                    "private_key": c_priv,
                    "public_key": c_pub,
                    "ip_v4": ip_v4,
                    "ip_v6": ip_v6,
                    "dns": dns,
                    "allowed_ips": allowed_ips,
                    "created_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                }
            },
            "next_offset": 3
        }
        
        self._save_cache()
        self.generate_server_conf()
        self.generate_client_conf(client_name)
        
        print(f"\n✅ 初始化完成！")
        print(f"📁 服务端配置: {(CONFIG_DIR / 'server' / f'{interface}.conf').absolute()}")
        print(f"📁 客户端配置: {(CONFIG_DIR / 'clients' / client_name / f'{client_name}.conf').absolute()}")
        print("💡 提示: 如需微调配置，请使用 vim/nano 编辑上述 .conf 文件，")
        print(f"       修改后运行: ./wg-manager.py qr {client_name} 重新生成二维码")
        print("-" * 50)
        self.show_qrcode(client_name)

    def cmd_add(self):
        if not self.cache:
            print("❌ 尚未初始化，请先运行 ./wg-manager.py init")
            return
            
        name = prompt("新客户端名称", "")
        if name in self.cache['clients']:
            print(f"❌ 客户端 {name} 已存在！")
            return
            
        offset = self.cache['next_offset']
        ip_v4 = get_ip_from_subnet(self.cache['server']['subnet_v4'], offset)
        ip_v6 = get_ip_from_subnet(self.cache['server']['subnet_v6'], offset)
        
        if not ip_v4 and not ip_v6:
            print("❌ IP 地址池已耗尽！")
            return

        c_priv = run(["wg", "genkey"])
        c_pub = run(["wg", "pubkey"], c_priv)
        
        first_client = next(iter(self.cache['clients'].values()))
        
        self.cache['clients'][name] = {
            "private_key": c_priv,
            "public_key": c_pub,
            "ip_v4": ip_v4,
            "ip_v6": ip_v6,
            "dns": first_client['dns'],
            "allowed_ips": first_client['allowed_ips'],
            "created_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        }
        self.cache['next_offset'] = offset + 1
        
        self._save_cache()
        self.generate_server_conf() 
        self.generate_client_conf(name)
        
        print(f"\n✅ 客户端 {name} 添加成功！")
        print(f"📁 配置文件: {(CONFIG_DIR / 'clients' / name / f'{name}.conf').absolute()}")
        print("💡 提示: 如需微调配置，请编辑上述文件，然后运行:")
        print(f"       ./wg-manager.py qr {name}")
        print("-" * 50)
        self.show_qrcode(name)

    def cmd_list(self):
        if not self.cache:
            print("❌ 尚未初始化")
            return
            
        srv = self.cache['server']
        print(f"\n📡 服务器: {srv['endpoint']}:{srv['listen_port']} (接口: {srv['interface']})")
        print("-" * 60)
        for name, c in self.cache['clients'].items():
            ips = []
            if c['ip_v4']: ips.append(c['ip_v4'])
            if c['ip_v6']: ips.append(c['ip_v6'])
            print(f"👤 {name:<15} | IP: {', '.join(ips):<25} | 创建: {c['created_at']}")
        print("-" * 60)

    def cmd_remove(self, name):
        if not self.cache:
            print("❌ 尚未初始化")
            return
        if name not in self.cache['clients']:
            print(f"❌ 找不到客户端 {name}")
            return
            
        ans = input(f"⚠️ 确定要删除客户端 {name} 吗？此操作不可逆 (y/N): ")
        if ans.lower() != 'y': return
        
        del self.cache['clients'][name]
        self._save_cache()
        
        c_dir = CONFIG_DIR / "clients" / name
        if c_dir.exists():
            shutil.rmtree(c_dir)
            
        self.generate_server_conf() 
        print(f"✅ 客户端 {name} 已删除，服务端配置已更新。")

    def cmd_qr_file(self, file_path):
        """针对任意指定路径的配置文件生成二维码"""
        self.show_qrcode_from_file(file_path)


def print_usage():
    print("""
🛡️ WireGuard 纯终端配置管理器 (wg-manager)

用法:
  ./wg-manager.py init                  # 交互式初始化服务器和第一个客户端
  ./wg-manager.py add                   # 添加新客户端并直接在终端打印二维码
  ./wg-manager.py list                  # 列出所有客户端
  ./wg-manager.py remove <name>         # 删除指定客户端
  ./wg-manager.py qr <name>             # 重新打印指定客户端的二维码
  ./wg-manager.py qr-file <文件路径>    # 针对任意路径的 .conf 文件生成二维码 (支持微调后使用)
""")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print_usage()
        sys.exit(1)
        
    try:
        run(["wg", "--version"])
    except FileNotFoundError:
        print("❌ 未找到 wg 命令，请安装 wireguard-tools")
        sys.exit(1)

    cmd = sys.argv[1]
    mgr = WGManager()
    
    if cmd == "init":
        mgr.cmd_init()
    elif cmd == "add":
        mgr.cmd_add()
    elif cmd == "list":
        mgr.cmd_list()
    elif cmd == "remove":
        if len(sys.argv) < 3:
            print("用法: ./wg-manager.py remove <client_name>")
            sys.exit(1)
        mgr.cmd_remove(sys.argv[2])
    elif cmd == "qr":
        if len(sys.argv) < 3:
            print("用法: ./wg-manager.py qr <client_name>")
            sys.exit(1)
        mgr.show_qrcode(sys.argv[2])
    elif cmd == "qr-file":
        if len(sys.argv) < 3:
            print("用法: ./wg-manager.py qr-file <配置文件路径>")
            sys.exit(1)
        mgr.cmd_qr_file(sys.argv[2])
    else:
        print_usage()